15 prometheus serice
P3-Hype/SRAMS-backend pull request #16
Opened 2023-10-24 12:35 UTC by Androkless

Prometheus service kan trække enkelte metrics ud. Gennem PromService.getmetric()
Kan også trække alle matrics fra et rum ud gennem AllMetrics.

Mangler error handling, hvis der ikke er connected en specifik sensor til rummet. Således kaster programmet en exception hvis PIR mangler, eksempelvis :-)))

2023-10-25 08:15 UTC, alexrefshauge requested changes
Det ser lækkert ud gutter, lige et par kommentarer

2023-10-25 08:15 UTC, alexrefshauge commented on src/main/java/p3/sramsbackend/PromData.java
> +    }
Tænker ikke det er nødvendigt med setter methoder, da vi kun læser fra prometheus.
Det samme gælder for de andre prometheus relaterede klasser 😊

2023-10-25 08:15 UTC, alexrefshauge commented on src/main/java/p3/sramsbackend/PromMetric.java
> +    public String get__name__() {
Kunne godt tænke mig et andet metode navn her 🤔
```suggestion
    public String getName() {
```

2023-10-25 08:15 UTC, alexrefshauge commented on src/main/java/p3/sramsbackend/metrics/AllMetrics.java
Var det denne her i snakkede om?

2023-10-25 08:15 UTC, alexrefshauge commented on src/main/java/p3/sramsbackend/metrics/Co2Metric.java
> +    final String co2Query = "_room_co2_level";
Kan denne variabel ikke blive nedarvet fra Metric, da de alle har en query?
De kan vel bare override varablen, og så er det vel lige før de specialiserede klasser ikke behøver at override getMetric()

2023-10-25 09:24 UTC, Androkless reviewed
Nu skulle ændringerne gerne være lavet

2023-10-25 09:27 UTC, Daniel-Rosbak-Student approved these changes
👍

2023-10-25 09:28 UTC, GustavHus commented on src/main/java/p3/sramsbackend/metrics/AllMetrics.java
Ja

2023-10-25 09:30 UTC, GustavHus commented
All good

2023-10-25 09:32 UTC, GustavHus approved these changes
Allllllll goooood

2023-10-25 09:39 UTC, alexrefshauge requested changes

2023-10-25 09:39 UTC, alexrefshauge commented on src/main/java/p3/sramsbackend/metrics/PromService.java
> +            return 0;
Hvorfor returnerer vi 0? Skal den ikke som minimum returnerer metric værdien?

2023-10-25 09:39 UTC, alexrefshauge commented on src/main/java/p3/sramsbackend/metrics/Co2Metric.java
> +    final String metricQuery = "_room_co2_level";
Husk @Override annotation
```suggestion
    @Override
    final String metricQuery = "_room_co2_level";
```

2023-10-25 09:39 UTC, alexrefshauge commented on src/main/java/p3/sramsbackend/metrics/HumidityMetric.java
> +    final String metricQuery = "_room_humidity";
```suggestion
    @Override
    final String metricQuery = "_room_humidity";
```

2023-10-25 09:39 UTC, alexrefshauge commented on src/main/java/p3/sramsbackend/metrics/PIRMetric.java
> +    final String metricQuery = "_room_pir";
```suggestion
    @Override
    final String metricQuery = "_room_pir";
```

2023-10-25 09:39 UTC, alexrefshauge commented on src/main/java/p3/sramsbackend/metrics/TemperatureMetric.java
> +    final String metricQuery = "_room_temperature";
```suggestion
    @Override
    final String metricQuery = "_room_temperature";
```

2023-10-25 09:39 UTC, alexrefshauge commented on src/main/java/p3/sramsbackend/PromMetricData.java
> +    }
```suggestion
```

2023-10-25 09:39 UTC, alexrefshauge commented on src/main/java/p3/sramsbackend/PromMetric.java
> +    }
```suggestion
```

2023-10-25 09:39 UTC, alexrefshauge commented on src/main/java/p3/sramsbackend/PromMetric.java
> +    }
```suggestion
```

2023-10-25 09:39 UTC, alexrefshauge commented on src/main/java/p3/sramsbackend/PromMetric.java
> +    }
```suggestion
```

2023-10-25 09:42 UTC, MathiasFM requested changes

2023-10-25 09:42 UTC, MathiasFM commented on src/main/java/p3/sramsbackend/PromResponse.java
> +// }
```suggestion
```

2023-10-25 09:42 UTC, MathiasFM commented on src/main/java/p3/sramsbackend/PromMetricData.java
> +// }]
```suggestion
```

2023-10-25 12:04 UTC, GustavHus commented on src/main/java/p3/sramsbackend/metrics/PromService.java
> +            return 0;
Vi retunere nu den hentede matric :)

2023-10-25 12:21 UTC, GustavHus commented on src/main/java/p3/sramsbackend/metrics/Co2Metric.java
> +    final String metricQuery = "_room_co2_level";
Fikset

2023-10-25 12:21 UTC, GustavHus commented on src/main/java/p3/sramsbackend/metrics/PIRMetric.java
> +    final String metricQuery = "_room_pir";
Fikset

2023-10-25 12:21 UTC, GustavHus commented on src/main/java/p3/sramsbackend/PromMetricData.java
> +    }
Fikset

2023-10-25 12:21 UTC, GustavHus commented on src/main/java/p3/sramsbackend/metrics/TemperatureMetric.java
> +    final String metricQuery = "_room_temperature";
Fikset

2023-10-25 12:23 UTC, GustavHus commented on src/main/java/p3/sramsbackend/PromMetric.java
> +    }
Slettet

2023-10-25 12:24 UTC, GustavHus commented on src/main/java/p3/sramsbackend/PromMetric.java
> +    }
slettet

2023-10-26 08:54 UTC, MathiasFM approved these changes

2023-10-30 19:21 UTC, alexrefshauge approved these changes

2023-10-30 19:23 UTC, alexrefshauge commented on src/main/java/p3/sramsbackend/metrics/PromService.java
> +    final static String prometheusURL = "http://161.35.193.69:9090/api/v1/query";
Let's just wait for the env variables/localsettings to be set up

2023-10-31 08:18 UTC, merged